#!/usr/bin/env node
// Quality Playbook Factory — rebuild derived views in a workspace.
//
//   1. Renders guidelines/guidelines.yml -> guidelines/guidelines.md (localized table).
//   2. Rebuilds wiki/index.md from the frontmatter of wiki pages.
//
// Usage: node rebuild-index.mjs [--dir <workspace path>]   (default: cwd)

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseYaml } from './lib/yaml.mjs';

const TOOL_ROOT = process.env.CLAUDE_PLUGIN_ROOT
  ? resolve(process.env.CLAUDE_PLUGIN_ROOT)
  : resolve(dirname(fileURLToPath(import.meta.url)), '..');

const argDir = (() => {
  const i = process.argv.indexOf('--dir');
  return i >= 0 ? process.argv[i + 1] : undefined;
})();
const WS = resolve(argDir || process.cwd());

function readYaml(p) { return parseYaml(readFileSync(p, 'utf8')); }

function frontmatter(md) {
  if (!md.startsWith('---')) return {};
  const end = md.indexOf('\n---', 3);
  if (end < 0) return {};
  return parseYaml(md.slice(3, end)) || {};
}

// --- load config ----------------------------------------------------------------
const cfgPath = join(WS, 'qpf.config.yml');
if (!existsSync(cfgPath)) {
  console.error(`✗ ${cfgPath} not found — is ${WS} a QPF workspace?`);
  process.exit(1);
}
const cfg = readYaml(cfgPath);
const lang = cfg.qpf?.language || 'en';
const customer = cfg.qpf?.customer || '';

// --- 1. render guidelines -------------------------------------------------------
function renderGuidelines() {
  const src = join(WS, 'guidelines', 'guidelines.yml');
  if (!existsSync(src)) { console.warn('! guidelines/guidelines.yml missing — skipped'); return; }
  const g = readYaml(src);
  const labels = readYaml(join(TOOL_ROOT, 'templates', 'guidelines', 'labels.yml'));
  const L = (m) => (labels[m][lang] || labels[m].en);
  const cols = L('columns');
  const typeLabels = L('types');
  const titles = L('section_titles');
  const doc = L('document');

  const lines = [];
  lines.push(`# ${doc.heading.replace('{customer}', customer)}`, '');
  lines.push(`<!-- DERIVED — rendered from guidelines.yml by rebuild-index. Do not hand-edit. -->`, '');
  lines.push(doc.intro, '');
  lines.push(`| ${cols.section} | ${cols.id} | ${cols.type} | ${cols.description} |`);
  lines.push('|---|---|---|---|');
  for (const s of g.sections || []) {
    const title = (titles && titles[String(s.number)]) || s.title || '';
    const sectionCell = `${s.number}. ${title}`;
    for (const it of s.items || []) {
      const type = (typeLabels[it.type] || it.type);
      const desc = String(it.description || '').replace(/\|/g, '\\|');
      lines.push(`| ${sectionCell} | ${it.id} | ${type} | ${desc} |`);
    }
  }
  lines.push('');
  writeFileSync(join(WS, 'guidelines', 'guidelines.md'), lines.join('\n'));
  const total = (g.sections || []).reduce((n, s) => n + (s.items?.length || 0), 0);
  console.log(`✓ guidelines.md rendered (${lang}) — ${total} items across ${(g.sections||[]).length} sections`);
}

// --- 2. rebuild wiki index ------------------------------------------------------
function listPages(subdir) {
  const dir = join(WS, 'wiki', subdir);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => {
      const fm = frontmatter(readFileSync(join(dir, f), 'utf8'));
      return {
        file: `wiki/${subdir}/${f}`,
        title: fm.title || f.replace(/\.md$/, ''),
        kind: fm.entity_kind,
        // OKF §8: index entries SHOULD carry the linked concept's own description.
        description: fm.description || '',
      };
    })
    .sort((a, b) => a.title.localeCompare(b.title));
}

function rebuildIndex() {
  // OKF v0.2 §8: an index carries no frontmatter, except that the bundle-root index
  // MAY declare `okf_version` — so that single key is all we emit. Entries follow the
  // §8 shape: `* [Title](url) - description`, grouped under headings.
  const out = [];
  out.push('---', 'okf_version: "0.2"', '---', '');
  out.push('<!-- DERIVED — regenerated by rebuild-index. Do not hand-edit. -->', '');

  const entry = (title, url, desc) => `* [${title}](${url})${desc ? ` - ${desc}` : ''}`;

  const overview = join(WS, 'wiki', 'overview.md');
  out.push('# Overview', '');
  if (existsSync(overview)) {
    const fm = frontmatter(readFileSync(overview, 'utf8'));
    out.push(entry(fm.title || 'Product / service overview', 'overview.md', fm.description || ''), '');
  } else {
    out.push('_none yet_', '');
  }

  for (const [heading, sub] of [['Summaries', 'summaries'], ['Entities', 'entities'], ['Concepts', 'concepts']]) {
    out.push(`# ${heading}`, '');
    const pages = listPages(sub);
    if (pages.length === 0) out.push('_none yet_', '');
    else {
      for (const p of pages) {
        const rel = relative(join(WS, 'wiki'), join(WS, p.file)).split('\\').join('/');
        // entity_kind is a QPF extension; keep it visible without breaking the §8 shape.
        const desc = [p.kind ? `(${p.kind})` : '', p.description].filter(Boolean).join(' ');
        out.push(entry(p.title, rel, desc));
      }
      out.push('');
    }
  }
  writeFileSync(join(WS, 'wiki', 'index.md'), out.join('\n'));
  const counts = ['summaries', 'entities', 'concepts'].map((s) => `${s}: ${listPages(s).length}`).join(', ');
  console.log(`✓ wiki/index.md rebuilt (${counts})`);
}

renderGuidelines();
rebuildIndex();
